In [24]:
import numpy as np

N Dimensional Pendulum

In [25]:
import AEMG.systems.ndpendulum as NdPendulum

In [26]:
ndpendulum = NdPendulum.NdPendulum(dims=9)

In [27]:
ndpendulum.transform([1,1])

array([3.26271593e-31, 1.30720469e-08, 2.68281110e-20, 3.37789932e-24,
       1.35335283e-01, 2.77752215e-13, 9.35588077e-26, 3.74842662e-03,
       7.69299605e-15])

4D Pendulum

In [28]:
import AEMG.systems.pendulum as Pendulum

In [29]:
pendulum = Pendulum.Pendulum()

In [30]:
pendulum.transform([1,1])

array([ 0.42073549,  0.27015115,  0.27015115, -0.42073549])

In [31]:
pendulum.transform(np.array([1,1]))

array([ 0.42073549,  0.27015115,  0.27015115, -0.42073549])

### From lower dimensional data to higher dimensional data

###### Save your data in PATH_TO/AEMG/examples/data

###### Pendulum

In [32]:
import os

In [33]:
dir_data_path = os.getcwd() + "/data/pendulum_lqr"
if not os.path.exists(dir_data_path):
    os.makedirs(dir_data_path)

###### save data in "dir_data_path" 

In [41]:
#### write your trajectories here

number_trajectories = 10

for counter in range(10):
    traj=[]
    
    
    state_temp = np.array([0,0])  # my trajectory data
    traj.append(state_temp)
    state_temp = np.array([0,1])  # my trajectory data
    traj.append(state_temp)

    traj = np.array(traj)
    np.savetxt(f"{dir_data_path}/{counter}.txt",traj,delimiter=",")

###### read data in "dir_data_path" with transformation

In [51]:
from AEMG.systems.utils import get_system

step = 1  # step 1 for the time series (xt)
Xt = []  # input
Xnext = []  # output
name_system = "pendulum" # desired system
dim = 4  # dimension of the system
system = get_system(name_system, dim)
for f in os.listdir(dir_data_path):
    data = np.loadtxt(os.path.join(dir_data_path, f), delimiter=',')
    for i in range(data.shape[0] - step):
        Xt.append(system.transform(data[i]))
        Xnext.append(system.transform(data[i + step]))

In [52]:
Xt  # input "x" of "y=f(x)"

[array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ]),
 array([ 0. ,  0.5,  0. , -0. ])]

In [53]:
Xnext # output "y" of "y=f(x)"

[array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ]),
 array([ 0. ,  0.5,  0.5, -0. ])]